spring:
  application:
    name: apolloAdminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: apolloconfig
    password: 123456
  jpa:
    show-sql: true

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log


