spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://192.168.37.85:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root
ctrip:
  appid: 100003171
  
server:
  port: 8080
  
logging:
  file: /opt/logs/100003171/apollo-configservice.log
