spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: apolloconfig
    password: 123456
ctrip:
  appid: 100003171
  
server:
  port: 8080
  
logging:
  file: /opt/logs/100003171/apollo-configservice.log
